trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
  AZURE_TENANT_ID: $(AZURE_TENANT_ID)
  AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
  KEY_VAULT_NAME: 'TestAccessControle'
  SECRET_NAME: 'SECRET-TOKEN'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'MyAzureSubscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      
      secret=$(az keyvault secret show --vault-name "$KEY_VAULT_NAME" --name "$SECRET_NAME" --query value -o tsv)
      
      echo "<settings>" > $(Build.SourcesDirectory)/settings.xml
      echo "  <servers>" >> $(Build.SourcesDirectory)/settings.xml
      echo "    <server>" >> $(Build.SourcesDirectory)/settings.xml
      echo "      <id>github</id>" >> $(Build.SourcesDirectory)/settings.xml
      echo "      <username>oleksandra-bulhakova</username>" >> $(Build.SourcesDirectory)/settings.xml
      echo "      <password>$secret</password>" >> $(Build.SourcesDirectory)/settings.xml
      echo "    </server>" >> $(Build.SourcesDirectory)/settings.xml
      echo "  </servers>" >> $(Build.SourcesDirectory)/settings.xml
      echo "</settings>" >> $(Build.SourcesDirectory)/settings.xml
  env:
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_TENANT_ID: $(AZURE_TENANT_ID)
    AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    options: '--settings $(Build.SourcesDirectory)/settings.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    mavenVersionOption: 'Default'
    
- script: |
        rm -f $(Build.SourcesDirectory)/settings.xml
  displayName: "Delete temporary settings.xml"